
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lflemweaktbptstkiukt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbGVtd2Vha3RicHRzdGtpdWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjA3MzgsImV4cCI6MjA1OTMzNjczOH0.h8XLapJ5uYNi9AtyGCariCtlO4Qzv71w8tsASzsYw8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true
    }
  }
);
